export const ROUTES = {
    HOME: '/',
    LOGIN: '/',
    DASHBOARD_FARMER: '/dashboard/farmer',
    DASHBOARD_ADMIN: '/dashboard/admin',
    CREATE_COOPERATIVE: '/create-cooperative',
    FIELD_INFO: '/field-information',
    CREATE_FIELD: '/field-information/create',
    PLOT_LIST: '/plot-list',
    CREATE_PLOT: '/plot-list/create',
    CROP_LIST: '/crop-list',
    CROP_DETAIL: '/crop-detail/:id',
    DEVICES: '/plots/:plotId/devices',
    LIVE_METRICS: '/plots/:plotId/metrics',
    USER_PROFILE: '/profile',
    CHAT: '/chat',
    IRRIGATION_CONTROL: '/irrigation-control',
    MANAGE_MEMBERS: '/members',
    INVENTORY: '/inventory',
    NOTFOUND: '*'
}